//COMMON 

export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";

//LOGIN

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const SET_USERNAME = "SET_USERNAME";
export const SET_LOGIN = "SET_LOGIN";
export const SET_THEME_SUCCESS = "SET_THEME_SUCCESS";
export const SET_THEME_FAILED = "SET_THEME_FAILED";


//NAVIGATION
export const NAVIGATING = "NAVIGATING";
export const NAVIGATE_SUCCESS = "NAVIGATE_SUCCESS";
export const NAVIGATE_FAILED = "NAVIGATE_FAILED";

//LORE PAGES

export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_FAILED = "FETCH_LIST_FAILED";
export const FETCH_PAGE_SUCCESS = "FETCH_PAGE_SUCCESS";
export const FETCH_PAGE_FAILED = "FETCH_PAGE_FAILED";
export const ADD_PAGE_SUCCESS = "ADD_PAGE_SUCCESS";
export const ADD_PAGE_FAILED = "ADD_PAGE_FAILED";
export const REMOVE_PAGE_SUCCESS = "REMOVE_PAGE_SUCCESS";
export const REMOVE_PAGE_FAILED = "REMOVE_PAGE_FAILED";
export const EDIT_PAGE_SUCCESS = "EDIT_PAGE_SUCCESS";
export const EDIT_PAGE_FAILED = "EDIT_PAGE_FAILED";
export const NO_PAGES_FOUND = "NO_PAGES_FOUND";

//CATEGORY PAGES

export const FETCH_CATEGORYLIST_SUCCESS = "FETCH_CATEGORYLIST_SUCCESS";
export const FETCH_CATEGORYLIST_FAILED = "FETCH_CATEGORYLIST_FAILED";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILED = "FETCH_CATEGORY_FAILED";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS";
export const REMOVE_CATEGORY_FAILED = "REMOVE_CATEGORY_FAILED";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAILED = "EDIT_CATEGORY_FAILED";
export const NO_CATEGORIES_FOUND = "NO_CATEGORIES_FOUND";

//WORLD PAGES

export const FETCH_WORLDLIST_SUCCESS = "FETCH_WORLDLIST_SUCCESS";
export const FETCH_WORLDLIST_FAILED = "FETCH_WORLDLIST_FAILED";
export const FETCH_WORLD_SUCCESS = "FETCH_WORLD_SUCCESS";
export const FETCH_WORLD_FAILED = "FETCH_WORLD_FAILED";
export const ADD_WORLD_SUCCESS = "ADD_WORLD_SUCCESS";
export const ADD_WORLD_FAILED = "ADD_WORLD_FAILED";
export const REMOVE_WORLD_SUCCESS = "REMOVE_WORLD_SUCCESS";
export const REMOVE_WORLD_FAILED = "REMOVE_WORLD_FAILED";
export const EDIT_WORLD_SUCCESS = "EDIT_WORLD_SUCCESS";
export const EDIT_WORLD_FAILED = "EDIT_WORLD_FAILED";
export const NO_WORLDS_FOUND = "NO_WORLDS_FOUND";